// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhbRh3XjmslpN8lyUIU7VDMHD1MUNQ854',
    appId: '1:98319394852:web:67cd38df43e99352e950b1',
    messagingSenderId: '98319394852',
    projectId: 'student-task-manager-54c0b',
    authDomain: 'student-task-manager-54c0b.firebaseapp.com',
    storageBucket: 'student-task-manager-54c0b.firebasestorage.app',
    measurementId: 'G-5N23YQ6YSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpanMuFI46QRsPDaejskII8XjkyOaGj6k',
    appId: '1:98319394852:android:d04828fb83d3c71be950b1',
    messagingSenderId: '98319394852',
    projectId: 'student-task-manager-54c0b',
    storageBucket: 'student-task-manager-54c0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKzFxLs7jMoJfSOnK1USPspUnKPRzg_gQ',
    appId: '1:98319394852:ios:b396c795f5d2626ae950b1',
    messagingSenderId: '98319394852',
    projectId: 'student-task-manager-54c0b',
    storageBucket: 'student-task-manager-54c0b.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKzFxLs7jMoJfSOnK1USPspUnKPRzg_gQ',
    appId: '1:98319394852:ios:b396c795f5d2626ae950b1',
    messagingSenderId: '98319394852',
    projectId: 'student-task-manager-54c0b',
    storageBucket: 'student-task-manager-54c0b.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhbRh3XjmslpN8lyUIU7VDMHD1MUNQ854',
    appId: '1:98319394852:web:8cc5ae609564a341e950b1',
    messagingSenderId: '98319394852',
    projectId: 'student-task-manager-54c0b',
    authDomain: 'student-task-manager-54c0b.firebaseapp.com',
    storageBucket: 'student-task-manager-54c0b.firebasestorage.app',
    measurementId: 'G-7KLZCJ3B5V',
  );
}
